services:
  app:
      image: "rain0r/stimmungskalender:2.0.0"
      container_name: "sk-app"
      env_file: .env
      ports:
        - "7890:8000"
      volumes:
        - "./logs:/logs"

volumes:
  static:
