services:
  app:
      image: "rain0r/stimmungskalender:2.0.0"
      container_name: "stimmungskalender"
      env_file: .env
      ports:
        - "7890:8000"
      volumes:
        - "./data:/data"
        - "static:/app/static"
volumes:
  static: