[project]
name = "stimmungskalender"
version = "2.0.0"
description = "Self-hosted mood calendar"
authors = [{ name = "Rainer Hihn", email = "hihn.rainer@gmail.com" }]
requires-python = ">= 3.14"
license = "AGPL-3.0-only"

dependencies = [
    "django==6.1.2",
    "dj-database-url==3.1.2",
    "django-cors-headers==4.9.0",
    "django-registration==5.2.1",
    "django-rosetta==0.10.3",
    "djangorestframework==3.18.3",
    "python-decouple==3.8",
    "uritemplate==4.2.0",
    "uwsgi==2.0.31",
    "djangorestframework-dataclasses==1.4.0",
]

[dependency-groups]
dev = [
    "ipdb==0.13.13",
]

[tool.djlint]
profile = "django"
