# Generated by Django 3.2.6 on 2021-08-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood_day",
                    models.IntegerField(
                        choices=[
                            (1, "Very Bad"),
                            (2, "Bad"),
                            (3, "Medium"),
                            (4, "Good"),
                            (5, "Very Good"),
                        ]
                    ),
                ),
                (
                    "mood_night",
                    models.IntegerField(
                        choices=[
                            (1, "Very Bad"),
                            (2, "Bad"),
                            (3, "Medium"),
                            (4, "Good"),
                            (5, "Very Good"),
                        ]
                    ),
                ),
                ("day", models.DateField()),
            ],
        ),
    ]
