# Generated by Django 3.2.6 on 2021-08-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="mood_day",
            field=models.IntegerField(
                choices=[
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Medium"),
                    (4, "Good"),
                    (5, "Very Good"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="mood_night",
            field=models.IntegerField(
                choices=[
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Medium"),
                    (4, "Good"),
                    (5, "Very Good"),
                ],
                null=True,
            ),
        ),
    ]
