# Generated by Django 3.2.6 on 2021-08-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_auto_20210806_1612"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.IntegerField()),
                ("notes", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="entry",
            name="notes",
        ),
    ]
