# Generated by Django 3.2.6 on 2021-08-06 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_auto_20210806_1638"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="notes",
            new_name="note",
        ),
    ]
