# Generated by Django 3.2.6 on 2021-08-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_auto_20210808_1819"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="year",
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
