# Generated by Django 3.2.9 on 2021-11-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_alter_usersettings_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="day",
            field=models.DateField(db_index=True),
        ),
    ]
