# Generated by Django 3.2.9 on 2021-11-15 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0011_alter_entry_day"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Note",
            new_name="Week",
        ),
    ]
