# Generated by Django 3.2.9 on 2021-11-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_rename_note_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="week_date",
            field=models.DateField(db_index=True, null=True),
        ),
    ]
