# Generated by Django 3.2.9 on 2021-11-15 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0013_week_week_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="week",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="web.week"
            ),
        ),
    ]
