# Generated by Django 3.2.9 on 2021-11-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_entry_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="week",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="week",
            name="week",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="week",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
