# Generated by Django 3.2.9 on 2021-11-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_auto_20211115_2119"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="week",
            name="week",
        ),
        migrations.RemoveField(
            model_name="week",
            name="year",
        ),
    ]
