# Generated by Django 3.2.9 on 2021-11-17 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0017_auto_20211117_1738"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="week",
            name="week",
        ),
        migrations.RemoveField(
            model_name="week",
            name="year",
        ),
    ]
