# Generated by Django 3.2.9 on 2021-11-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0018_auto_20211117_1908"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="week",
            constraint=models.UniqueConstraint(
                fields=("user", "week_date"), name="unique entry"
            ),
        ),
    ]
