# Generated by Django 4.0.5 on 2022-06-22 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0022_usersettings_view_day_form_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMoodColorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood",
                    models.IntegerField(
                        choices=[
                            (1, "Very Bad"),
                            (2, "Bad"),
                            (3, "Medium"),
                            (4, "Good"),
                            (5, "Very Good"),
                        ]
                    ),
                ),
                ("color", models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="week",
            name="unique entry",
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(
                fields=("user", "day"), name="Unique user and day"
            ),
        ),
        migrations.AddConstraint(
            model_name="week",
            constraint=models.UniqueConstraint(
                fields=("user", "week_date"), name="Unique user and week_date"
            ),
        ),
        migrations.AddField(
            model_name="usermoodcolorsettings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
